version: '3.8'

services:
  web:
    build: .
    command: gunicorn Sale360.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Monta todo el proyecto en el contenedor
      - ./dashboard/static:/app/dashboard/static  # Monta específicamente el directorio de arch
      - ./media:/app/media
    ports:
      - "8003:8000"
    env_file: # Referencia al archivo .env
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file: # Referencia al archivo .env
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
